-- Add exam date to users table
alter table users add column if not exists exam_date date;

-- Weekly study plans generated by AI
create table if not exists study_plans (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid references users(id) on delete cascade not null,
  exam_date    date not null,
  plan         jsonb not null,
  generated_at timestamptz default now(),
  is_active    boolean default true
);

create index on study_plans (user_id, is_active);
